# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

if Quiz.count == 0 
	Quiz.create!(title: 'Which of the following cities is known as Electronic City of India ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'Ms Bachendri Pal had undertaken a unique expedition for focussing attention on which of the following themes ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'Where is teh National Remote Sensing Agency situated ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'The first underground railway in India was opened in 1984 in', type: 'QuizLevelOne')
	Quiz.create!(title: 'Ashok Pandit is known for his outstanding performance in which of the following ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'Who was the first Indian to go into space ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'Who wrote Dragons Seed ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'Bismillah Khan is associated with', type: 'QuizLevelOne')
	Quiz.create!(title: 'The Paratroopers Training School of the Indian Air Force, is located at', type: 'QuizLevelOne')
	Quiz.create!(title: 'The famous Meenakshi temple is in', type: 'QuizLevelOne')
	Quiz.create!(title: 'Which of the following personalities inspiredGreen Revolution in India ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'The headquarters of the National Power Training Institute is located in', type: 'QuizLevelOne')
	Quiz.create!(title: 'Which of the following is a violin player ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'Which Iraqi scientist known as Dr. Germ for her role in Iraqs biological weapons programme recently surrendered to coalition forces ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'Kishori Amonkar is famous in which of the following fields ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'Guru Gopinath was an exponent of', type: 'QuizLevelOne')
	Quiz.create!(title: 'A. Nageshwara Rao is asociated which of the following fields ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'The world famous ajanta caves are situated in the state of', type: 'QuizLevelOne')
	Quiz.create!(title: 'The Indial Institute of Science is located at', type: 'QuizLevelOne')
	Quiz.create!(title: 'Which among the following ranks in Indian Air Force is the highest ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'Which music director had the distinction of being the first Asian to compose a symphony for Royal Philharmonic Orchestra of London ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'National Science Centre is located at', type: 'QuizLevelOne')
	Quiz.create!(title: 'Who is Mickey Kantor ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'When was the first air-conditioned train introduced in India ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'Who among the following was the first woman Chief Justice of a High Court ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'The first English newspaper in India was started by', type: 'QuizLevelOne')
	Quiz.create!(title: 'The National Design Institute is located at', type: 'QuizLevelOne')
	Quiz.create!(title: 'The Centre for Cellular amd Molecular Biology is situated at', type: 'QuizLevelOne')
	Quiz.create!(title: 'The Rajiv Gandhi National Institute of Youth Development has been set up at which of the following places ?', type: 'QuizLevelOne')
	Quiz.create!(title: 'Ustad Vilayat Khan is associated with', type: 'QuizLevelOne')
	Quiz.create!(title: 'Who among the following is the famous renowned astronomer (recipient of Padma Bhushan Award at the age of 27) ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'C.D.R.I. is located at', type: 'QuizLevelTwo')
	Quiz.create!(title: 'The first nuclear reactor in India is', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Eight Lives is a book written by', type: 'QuizLevelTwo')
	Quiz.create!(title: 'First Governor General of India, after independence was', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Which of the following pairs is incorrect ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Malvika Sarukkain is a famous exponent of', type: 'QuizLevelTwo')
	Quiz.create!(title: 'The National Physical Laboratory is located in', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Who is the youngest player to score a century in test cricket ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Late G. Aravindan was associated with which of the following fields ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'The Lal Bahadur Shastri Academy which trains Indian Administrative Services (IAS) officers is situated at', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Late Sri K. Shankar Pillai was associated with wich of the following fields ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'The first field Marshal of India was', type: 'QuizLevelTwo')
	Quiz.create!(title: 'In which of the following cities Lal Bahadur Stadium is located ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Who among the following is a famous table player ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Headquarters of the newly created South-Western Railway Zone is locate at', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Indian Cancer Research Institute is located at', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Pady Clarke Ha Ha Ha, a very popular book, is written by', type: 'QuizLevelTwo')
	Quiz.create!(title: 'The headquarters of the National Reaserch Laboratory for Conservation of Cultural Property is located in', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Prof. Amartya Sen has earned worldwide distinction in which of the following fields/areas ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Vikram sarabhi Space Centre is located at', type: 'QuizLevelTwo')
	Quiz.create!(title: 'A Who among the following topped the Forbes magazines annual list of the Planet released in June 2002 ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Whose Samadhi in Delhi is called Vijay Ghat ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Indian School of Mines is located in which of the following cities ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Greto Garbo is a name associated with', type: 'QuizLevelTwo')
	Quiz.create!(title: 'With which of the following w Satyajit Ray associated ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Who among the following was an eminent Painter ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Mr. Shah lal has done commendable work in which of the following fields ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'Who among the following persons is called Desert Fox ?', type: 'QuizLevelTwo')
	Quiz.create!(title: 'The National Institute of Community Development is located at', type: 'QuizLevelTwo')
	Quiz.create!(title: 'National Institute of Aeronautical Engineering is located at', type: 'QuizLevelThree')
	Quiz.create!(title: 'The first Financial service Park for industry is being set up at', type: 'QuizLevelThree')
	Quiz.create!(title: 'Where is the National Defence College situated ?', type: 'QuizLevelThree')
	Quiz.create!(title: 'The Dr. Babasaheb Ambedkar Maharathwada University is at which of the following place ?', type: 'QuizLevelThree')
	Quiz.create!(title: 'The largest and the oldest museum of India is located in the state/union territory of', type: 'QuizLevelThree')
	Quiz.create!(title: 'Golden Temple is situated in', type: 'QuizLevelThree')
	Quiz.create!(title: 'Guru Kelucharan Mohapatra is a maestro of which of the following dance forms ?', type: 'QuizLevelThree')
	Quiz.create!(title: 'Who among the following is not reputed as a painter ?', type: 'QuizLevelThree')
	Quiz.create!(title: 'Which of the following names are associated with classical music ? 1. Swami Haridas 2. Syama Shastri 3. Thyagaraja', type: 'QuizLevelThree')
	Quiz.create!(title: 'The man popularly known as Gurudev is', type: 'QuizLevelThree')
	Quiz.create!(title: 'Guru Gopi Krishna was a maestro of which of the following dance forms ?', type: 'QuizLevelThree')
	Quiz.create!(title: 'Shiv Kumar Sharma is a famous player of', type: 'QuizLevelThree')
	Quiz.create!(title: 'The largest dry dock in Indial is situated at', type: 'QuizLevelThree')
	Quiz.create!(title: 'Indias first Ladies Special Subruban train was started by which of the following zones of Inidian Railways ?', type: 'QuizLevelThree')
	Quiz.create!(title: 'Consider the following statments about Dalai Lama : 1. After fleeing Tibet, he settled down in Dharamsala. 2. He was awarded the Nobel Prize in 1989. 3. His Government in exile has not been recognised by any country. 4. Karmappa of the Rumtek Monastery has been mamed as his successor.Of these statements, the correct ones are', type: 'QuizLevelThree')
	Quiz.create!(title: 'Ms. Harita Kaur has the distinction of being the first Indian woman', type: 'QuizLevelThree')
	Quiz.create!(title: 'If you want to visit Lumbini, the birth of Gautam Buddha, you will have to go to', type: 'QuizLevelThree')
	Quiz.create!(title: 'Who is considered as Trimurti (Trinity) of Carnatic Music ?', type: 'QuizLevelThree')
	Quiz.create!(title: 'Who among the following was the creator of the Barbie, the worlds most popular doll ?', type: 'QuizLevelThree')
	Quiz.create!(title: 'Mandi House is', type: 'QuizLevelThree')
	Quiz.create!(title: 'First railway line in India was laid in', type: 'QuizLevelThree')
	Quiz.create!(title: 'The Central Scientific Instruments Organisation is situated at', type: 'QuizLevelThree')
	Quiz.create!(title: 'Which of the following associations of artists and their art or instrument is wrong ?', type: 'QuizLevelThree')
	Quiz.create!(title: 'Bhau Athaya won an Oscar award for', type: 'QuizLevelThree')
	Quiz.create!(title: 'Who among the following has been conferred the Honorary Knight Commander of the British Empire by Queen Elizabeth II in recognition of his/her services to music ?', type: 'QuizLevelThree')
	Quiz.create!(title: 'National Police Academy is located at', type: 'QuizLevelThree')
	Quiz.create!(title: 'Jawaharlal Nehru Pattan is located in which of the following state ?', type: 'QuizLevelThree')
	Quiz.create!(title: 'The Vivekananda Rock Memoria is situated at which of the following places ?', type: 'QuizLevelThree')
	Quiz.create!(title: 'Patwarilal Das was a/an', type: 'QuizLevelThree')
	Quiz.create!(title: 'Tin Bigha lease by India to Bangladesh, was a part of', type: 'QuizLevelThree')


end

if QuizOption.count == 0

	QuizOption.create!(option: 'Mumbai', correct: false, value: 0, quiz_id: 1)
	QuizOption.create!(option: 'Hyderabad', correct: false, value: 0, quiz_id: 1)
	QuizOption.create!(option: 'Bangalore', correct: true, value: 1, quiz_id: 1)
	QuizOption.create!(option: 'Gurgaon', correct: false, value: 0, quiz_id: 1)
	QuizOption.create!(option: 'Chennai', correct: false, value: 0, quiz_id: 1)

	QuizOption.create!(option: 'National Integration', correct: false, value: 0, quiz_id: 2)
	QuizOption.create!(option: 'The Girl Child', correct: false, value: 0, quiz_id: 2)
	QuizOption.create!(option: 'Spirit of Adventure', correct: true, value: 1, quiz_id: 2)
	QuizOption.create!(option: 'One Nation One Family', correct: false, value: 0, quiz_id: 2)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 2)

	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 3)
	QuizOption.create!(option: 'Dehradun', correct: false, value: 0, quiz_id: 3)
	QuizOption.create!(option: 'Shadnagar', correct: true, value: 1, quiz_id: 3)
	QuizOption.create!(option: 'Chennai', correct: false, value: 0, quiz_id: 3)
	QuizOption.create!(option: 'Hyderabad', correct: false, value: 0, quiz_id: 3)

	QuizOption.create!(option: 'Mumbai', correct: false, value: 0, quiz_id: 4)
	QuizOption.create!(option: 'Kolkata', correct: true, value: 1, quiz_id: 4)
	QuizOption.create!(option: 'Chennai', correct: false, value: 0, quiz_id: 4)
	QuizOption.create!(option: 'Delhi', correct: false, value: 0, quiz_id: 4)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 4)

	QuizOption.create!(option: 'Shooting', correct: true, value: 1, quiz_id: 5)
	QuizOption.create!(option: 'Wrestling', correct: false, value: 0, quiz_id: 5)
	QuizOption.create!(option: 'Swimming', correct: false, value: 0, quiz_id: 5)
	QuizOption.create!(option: 'Kabaddi', correct: false, value: 0, quiz_id: 5)
	QuizOption.create!(option: 'Chess', correct: false, value: 0, quiz_id: 5)

	QuizOption.create!(option: 'Satish Dhawan', correct: false, value: 0, quiz_id: 6)
	QuizOption.create!(option: 'Ravi Malhotra', correct: false, value: 0, quiz_id: 6)
	QuizOption.create!(option: 'Kalpana Chawla', correct: false, value: 0, quiz_id: 6)
	QuizOption.create!(option: 'Rakesh Sharma', correct: true, value: 1, quiz_id: 6)
	QuizOption.create!(option: 'None of these', correct: false, value: 0, quiz_id: 6)

	QuizOption.create!(option: 'Pearl S. Buck', correct: true, value: 1, quiz_id: 7)
	QuizOption.create!(option: 'Shakespeare', correct: false, value: 0, quiz_id: 7)
	QuizOption.create!(option: 'Shelley', correct: false, value: 0, quiz_id: 7)
	QuizOption.create!(option: 'Keats', correct: false, value: 0, quiz_id: 7)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 7)

	QuizOption.create!(option: 'Tabla', correct: false, value: 0, quiz_id: 8)
	QuizOption.create!(option: 'Sarod', correct: false, value: 0, quiz_id: 8)
	QuizOption.create!(option: 'Flute', correct: false, value: 0, quiz_id: 8)
	QuizOption.create!(option: 'Shehnai', correct: true, value: 1, quiz_id: 8)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 8)

	QuizOption.create!(option: 'Nasik', correct: false, value: 0, quiz_id: 9)
	QuizOption.create!(option: 'Agra', correct: true, value: 1, quiz_id: 9)
	QuizOption.create!(option: 'Pune', correct: false, value: 0, quiz_id: 9)
	QuizOption.create!(option: 'Dehradun', correct: false, value: 0, quiz_id: 9)
	QuizOption.create!(option: 'None Of the above', correct: false, value: 0, quiz_id: 9)

	QuizOption.create!(option: 'Maharashtra', correct: false, value: 0, quiz_id: 10)
	QuizOption.create!(option: 'Gujarat', correct: false, value: 0, quiz_id: 10)
	QuizOption.create!(option: 'Orissa', correct: false, value: 0, quiz_id: 10)
	QuizOption.create!(option: 'Tamil Nadu', correct: true, value: 1, quiz_id: 10)
	QuizOption.create!(option: 'Karnataka', correct: false, value: 0, quiz_id: 10)

	QuizOption.create!(option: 'R.A. Kidwai', correct: false, value: 0, quiz_id: 11)
	QuizOption.create!(option: 'N.E. Borlaug', correct: true, value: 1, quiz_id: 11)
	QuizOption.create!(option: 'K.M. Panikkar', correct: false, value: 0, quiz_id: 11)
	QuizOption.create!(option: 'M.S. Ssaminathan', correct: false, value: 0, quiz_id: 11)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 11)

	QuizOption.create!(option: 'Lucknow', correct: false, value: 0, quiz_id: 12)
	QuizOption.create!(option: 'Faridabad', correct: true, value: 1, quiz_id: 12)
	QuizOption.create!(option: 'Bhopal', correct: false, value: 0, quiz_id: 12)
	QuizOption.create!(option: 'Hyderabad', correct: false, value: 0, quiz_id: 12)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 12)

	QuizOption.create!(option: 'V.C. Jog', correct: true, value: 1, quiz_id: 13)
	QuizOption.create!(option: 'Mallikarjun Mansur', correct: false, value: 0, quiz_id: 13)
	QuizOption.create!(option: 'Hariprasad Chaurasia', correct: false, value: 0, quiz_id: 13)
	QuizOption.create!(option: 'a & b', correct: false, value: 0, quiz_id: 13)
	QuizOption.create!(option: 'None of these', correct: false, value: 0, quiz_id: 13)

	QuizOption.create!(option: 'Maleeha Lodhi', correct: false, value: 0, quiz_id: 14)
	QuizOption.create!(option: 'Salma Pervez', correct: false, value: 0, quiz_id: 14)
	QuizOption.create!(option: 'Saleema Garib', correct: false, value: 0, quiz_id: 14)
	QuizOption.create!(option: 'Rihab Rashid Taha', correct: true, value: 1, quiz_id: 14)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 14)

	QuizOption.create!(option: 'Dance', correct: false, value: 0, quiz_id: 15)
	QuizOption.create!(option: 'Music', correct: true, value: 1, quiz_id: 15)
	QuizOption.create!(option: 'Social service', correct: false, value: 0, quiz_id: 15)
	QuizOption.create!(option: 'Film acting', correct: false, value: 0, quiz_id: 15)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 15)

	QuizOption.create!(option: 'Kuchipudi', correct: false, value: 0, quiz_id: 16)
	QuizOption.create!(option: 'Bharatnatyam', correct: false, value: 0, quiz_id: 16)
	QuizOption.create!(option: 'Kathakali', correct: true, value: 1, quiz_id: 16)
	QuizOption.create!(option: 'Kathak', correct: false, value: 0, quiz_id: 16)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 16)

	QuizOption.create!(option: 'Sports', correct: false, value: 0, quiz_id: 17)
	QuizOption.create!(option: 'Social service', correct: false, value: 0, quiz_id: 17)
	QuizOption.create!(option: 'Literature', correct: false, value: 0, quiz_id: 17)
	QuizOption.create!(option: 'Motion Picture', correct: true, value: 1, quiz_id: 17)
	QuizOption.create!(option: 'Dance', correct: false, value: 0, quiz_id: 17)

	QuizOption.create!(option: 'Madhya Pradesh', correct: false, value: 0, quiz_id: 18)
	QuizOption.create!(option: 'Maharashtra', correct: true, value: 1, quiz_id: 18)
	QuizOption.create!(option: 'Karnataka', correct: false, value: 0, quiz_id: 18)
	QuizOption.create!(option: 'Orissa', correct: false, value: 0, quiz_id: 18)
	QuizOption.create!(option: 'Tamilnadu', correct: false, value: 0, quiz_id: 18)

	QuizOption.create!(option: 'New Delhi', correct: false, value: 0, quiz_id: 19)
	QuizOption.create!(option: 'Madras', correct: false, value: 0, quiz_id: 19)
	QuizOption.create!(option: 'Kharagpur', correct: false, value: 0, quiz_id: 19)
	QuizOption.create!(option: 'Bangalore', correct: true, value: 1, quiz_id: 19)
	QuizOption.create!(option: 'Hyderabad', correct: false, value: 0, quiz_id: 19)

	QuizOption.create!(option: 'Flying Officer', correct: false, value: 0, quiz_id: 20)
	QuizOption.create!(option: 'Air Commodore', correct: true, value: 1, quiz_id: 20)
	QuizOption.create!(option: 'Wing Commander', correct: false, value: 0, quiz_id: 20)
	QuizOption.create!(option: 'Squadron Leader', correct: false, value: 0, quiz_id: 20)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 20)

	QuizOption.create!(option: 'Nadeem - Sharavan', correct: false, value: 0, quiz_id: 21)
	QuizOption.create!(option: 'Anand - Milind', correct: false, value: 0, quiz_id: 21)
	QuizOption.create!(option: 'Shiv Hari', correct: false, value: 0, quiz_id: 21)
	QuizOption.create!(option: 'Ilayaraja', correct: false, value: 0, quiz_id: 21)
	QuizOption.create!(option: 'None of these', correct: true, value: 1, quiz_id: 21)

	QuizOption.create!(option: 'Delhi', correct: true, value: 1, quiz_id: 22)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 22)
	QuizOption.create!(option: 'Bombay', correct: false, value: 0, quiz_id: 22)
	QuizOption.create!(option: 'Kolkata', correct: false, value: 0, quiz_id: 22)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 22)

	QuizOption.create!(option: 'U.S. trade representative', correct: true, value: 1, quiz_id: 23)
	QuizOption.create!(option: 'American Noble Prize winner for Economics', correct: false, value: 0, quiz_id: 23)
	QuizOption.create!(option: 'U.S. Film actress', correct: false, value: 0, quiz_id: 23)
	QuizOption.create!(option: 'Wife of a former Americal President', correct: false, value: 0, quiz_id: 23)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 23)

	QuizOption.create!(option: '1936', correct: true, value: 1, quiz_id: 24)
	QuizOption.create!(option: '1946', correct: false, value: 0, quiz_id: 24)
	QuizOption.create!(option: '1969', correct: false, value: 0, quiz_id: 24)
	QuizOption.create!(option: '1975', correct: false, value: 0, quiz_id: 24)
	QuizOption.create!(option: '1956', correct: false, value: 0, quiz_id: 24)

	QuizOption.create!(option: 'Geeta Mukherjee', correct: false, value: 0, quiz_id: 25)
	QuizOption.create!(option: 'Leila Seth', correct: true, value: 1, quiz_id: 25)
	QuizOption.create!(option: 'Sujata Manohar', correct: false, value: 0, quiz_id: 25)
	QuizOption.create!(option: 'Rani Jethmalani', correct: false, value: 0, quiz_id: 25)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 25)

	QuizOption.create!(option: 'Dadabhai Naoroji', correct: false, value: 0, quiz_id: 26)
	QuizOption.create!(option: 'J.A. Hickey', correct: true, value: 1, quiz_id: 26)
	QuizOption.create!(option: 'Lord William Bentinck', correct: false, value: 0, quiz_id: 26)
	QuizOption.create!(option: 'Rabindranath Tagore', correct: false, value: 0, quiz_id: 26)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 26)

	QuizOption.create!(option: 'Hyderabad', correct: false, value: 0, quiz_id: 27)
	QuizOption.create!(option: 'Chandigarh', correct: false, value: 0, quiz_id: 27)
	QuizOption.create!(option: 'Ahmedabad', correct: true, value: 1, quiz_id: 27)
	QuizOption.create!(option: 'Dehradun', correct: false, value: 0, quiz_id: 27)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 27)

	QuizOption.create!(option: 'New Delhi', correct: false, value: 0, quiz_id: 28)
	QuizOption.create!(option: 'Hyderabad', correct: false, value: 0, quiz_id: 28)
	QuizOption.create!(option: 'Patna', correct: false, value: 0, quiz_id: 28)
	QuizOption.create!(option: 'Jaipur', correct: true, value: 1, quiz_id: 28)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 28)

	QuizOption.create!(option: 'Lucknow', correct: false, value: 0, quiz_id: 29)
	QuizOption.create!(option: 'Bombay', correct: false, value: 0, quiz_id: 29)
	QuizOption.create!(option: 'New Delhi', correct: false, value: 0, quiz_id: 29)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 29)
	QuizOption.create!(option: 'None of these', correct: true, value: 1, quiz_id: 29)

	QuizOption.create!(option: 'painting', correct: false, value: 0, quiz_id: 30)
	QuizOption.create!(option: 'classical music', correct: false, value: 0, quiz_id: 30)
	QuizOption.create!(option: 'light music', correct: false, value: 0, quiz_id: 30)
	QuizOption.create!(option: 'instrumental music', correct: true, value: 1, quiz_id: 30)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 30)

	QuizOption.create!(option: 'Prof. S.S. Joshi', correct: false, value: 0, quiz_id: 31)
	QuizOption.create!(option: 'Dr. Subramaniam Chandrashekhar', correct: false, value: 0, quiz_id: 31)
	QuizOption.create!(option: 'Prof. Satish Dhawan', correct: false, value: 0, quiz_id: 31)
	QuizOption.create!(option: 'Dr. Jayant Vishnu Narlikar', correct: true, value: 1, quiz_id: 31)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 31)

	QuizOption.create!(option: 'Lucknow', correct: true, value: 1, quiz_id: 32)
	QuizOption.create!(option: 'Mysore', correct: false, value: 0, quiz_id: 32)
	QuizOption.create!(option: 'Nagpur', correct: false, value: 0, quiz_id: 32)
	QuizOption.create!(option: 'Madras', correct: false, value: 0, quiz_id: 32)
	QuizOption.create!(option: 'Delhi', correct: false, value: 0, quiz_id: 32)

	QuizOption.create!(option: 'Dhruva', correct: false, value: 0, quiz_id: 33)
	QuizOption.create!(option: 'Harsha', correct: false, value: 0, quiz_id: 33)
	QuizOption.create!(option: 'Apsara', correct: true, value: 1, quiz_id: 33)
	QuizOption.create!(option: 'Vipula', correct: false, value: 0, quiz_id: 33)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 33)

	QuizOption.create!(option: 'Khushwant Singh', correct: false, value: 0, quiz_id: 34)
	QuizOption.create!(option: 'Mahesh Yogi', correct: false, value: 0, quiz_id: 34)
	QuizOption.create!(option: 'Raj Mohan Gandhi', correct: true, value: 1, quiz_id: 34)
	QuizOption.create!(option: 'Savita Ambedkar', correct: false, value: 0, quiz_id: 34)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 34)

	QuizOption.create!(option: 'C. Rajagopalachari', correct: false, value: 0, quiz_id: 35)
	QuizOption.create!(option: 'Jawaharlal Nehru', correct: false, value: 0, quiz_id: 35)
	QuizOption.create!(option: 'Lord Mountbatten', correct: true, value: 1, quiz_id: 35)
	QuizOption.create!(option: 'Rajendra Prasad', correct: false, value: 0, quiz_id: 35)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 35)

	QuizOption.create!(option: 'Pannalal Ghosh - Flute', correct: false, value: 0, quiz_id: 36)
	QuizOption.create!(option: 'Nikhil Banerjee - Santoor', correct: true, value: 1, quiz_id: 36)
	QuizOption.create!(option: 'V.C. Jog - Violin', correct: false, value: 0, quiz_id: 36)
	QuizOption.create!(option: 'Hari Prasad Chaurasia - Flute', correct: false, value: 0, quiz_id: 36)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 36)

	QuizOption.create!(option: 'Kathak', correct: false, value: 0, quiz_id: 37)
	QuizOption.create!(option: 'Odissi', correct: false, value: 0, quiz_id: 37)
	QuizOption.create!(option: 'Kuchipudi', correct: true, value: 1, quiz_id: 37)
	QuizOption.create!(option: 'Kathakali', correct: false, value: 0, quiz_id: 37)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 37)

	QuizOption.create!(option: 'Delhi', correct: true, value: 1, quiz_id: 38)
	QuizOption.create!(option: 'Calcutta', correct: false, value: 0, quiz_id: 38)
	QuizOption.create!(option: 'Hyderabad', correct: false, value: 0, quiz_id: 38)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 38)
	QuizOption.create!(option: 'Chennai', correct: false, value: 0, quiz_id: 38)

	QuizOption.create!(option: 'Haneef Mohammed', correct: false, value: 0, quiz_id: 39)
	QuizOption.create!(option: 'Mohd. Azharuddin', correct: false, value: 0, quiz_id: 39)
	QuizOption.create!(option: 'S.Gavaskar', correct: false, value: 0, quiz_id: 39)
	QuizOption.create!(option: 'S.Tendulkar', correct: true, value: 1, quiz_id: 39)
	QuizOption.create!(option: 'Yuvraj', correct: false, value: 0, quiz_id: 39)

	QuizOption.create!(option: 'Sports', correct: false, value: 0, quiz_id: 40)
	QuizOption.create!(option: 'Journalism', correct: false, value: 0, quiz_id: 40)
	QuizOption.create!(option: 'Politics', correct: false, value: 0, quiz_id: 40)
	QuizOption.create!(option: 'Motion Picture', correct: true, value: 1, quiz_id: 40)
	QuizOption.create!(option: 'Dance', correct: false, value: 0, quiz_id: 40)

	QuizOption.create!(option: 'Mussoorie', correct: true, value: 1, quiz_id: 41)
	QuizOption.create!(option: 'Dehradun', correct: false, value: 0, quiz_id: 41)
	QuizOption.create!(option: 'Srinagar', correct: false, value: 0, quiz_id: 41)
	QuizOption.create!(option: 'Khandala', correct: false, value: 0, quiz_id: 41)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 41)

	QuizOption.create!(option: 'Social service', correct: false, value: 0, quiz_id: 42)
	QuizOption.create!(option: 'Cartooning', correct: true, value: 1, quiz_id: 42)
	QuizOption.create!(option: 'Motion Pictures', correct: false, value: 0, quiz_id: 42)
	QuizOption.create!(option: 'Music', correct: false, value: 0, quiz_id: 42)
	QuizOption.create!(option: 'Dance', correct: false, value: 0, quiz_id: 42)

	QuizOption.create!(option: 'A. Vaidya', correct: false, value: 0, quiz_id: 43)
	QuizOption.create!(option: 'K.M. Cariappa', correct: false, value: 0, quiz_id: 43)
	QuizOption.create!(option: 'Sunder ji', correct: false, value: 0, quiz_id: 43)
	QuizOption.create!(option: 'S.H.F.J. Manekshaw', correct: true, value: 1, quiz_id: 43)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 43)

	QuizOption.create!(option: 'Lucknow', correct: false, value: 0, quiz_id: 44)
	QuizOption.create!(option: 'Kolkata', correct: false, value: 0, quiz_id: 44)
	QuizOption.create!(option: 'Hyderabad', correct: true, value: 1, quiz_id: 44)
	QuizOption.create!(option: 'Cuttack', correct: false, value: 0, quiz_id: 44)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 44)

	QuizOption.create!(option: 'Ali Akbar Khan', correct: false, value: 0, quiz_id: 45)
	QuizOption.create!(option: 'Birju Maharaj', correct: false, value: 0, quiz_id: 45)
	QuizOption.create!(option: 'Ravi Shanker', correct: false, value: 0, quiz_id: 45)
	QuizOption.create!(option: 'Swappan Kumar', correct: true, value: 1, quiz_id: 45)
	QuizOption.create!(option: '', correct: false, value: 0, quiz_id: 45)

	QuizOption.create!(option: 'Jabalpur', correct: false, value: 0, quiz_id: 46)
	QuizOption.create!(option: 'Hubli', correct: true, value: 1, quiz_id: 46)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 46)
	QuizOption.create!(option: 'Bhopal', correct: false, value: 0, quiz_id: 46)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 46)

	QuizOption.create!(option: 'Delhi', correct: false, value: 0, quiz_id: 47)
	QuizOption.create!(option: 'Calcutta', correct: false, value: 0, quiz_id: 47)
	QuizOption.create!(option: 'Mumbai', correct: true, value: 1, quiz_id: 47)
	QuizOption.create!(option: 'Chennai', correct: false, value: 0, quiz_id: 47)
	QuizOption.create!(option: 'Hyderabad', correct: false, value: 0, quiz_id: 47)

	QuizOption.create!(option: 'Norman Angell', correct: false, value: 0, quiz_id: 48)
	QuizOption.create!(option: 'Roddy Doyle', correct: true, value: 1, quiz_id: 48)
	QuizOption.create!(option: 'Arnold Tonybee', correct: false, value: 0, quiz_id: 48)
	QuizOption.create!(option: 'Juan Benet', correct: false, value: 0, quiz_id: 48)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 48)

	QuizOption.create!(option: 'Jaipur', correct: false, value: 0, quiz_id: 49)
	QuizOption.create!(option: 'Delhi', correct: false, value: 0, quiz_id: 49)
	QuizOption.create!(option: 'Pune', correct: false, value: 0, quiz_id: 49)
	QuizOption.create!(option: 'Lucknow', correct: true, value: 1, quiz_id: 49)
	QuizOption.create!(option: 'Chennai', correct: false, value: 0, quiz_id: 49)

	QuizOption.create!(option: 'Economics', correct: true, value: 1, quiz_id: 50)
	QuizOption.create!(option: 'Geology', correct: false, value: 0, quiz_id: 50)
	QuizOption.create!(option: 'Biochemistry', correct: false, value: 0, quiz_id: 50)
	QuizOption.create!(option: 'Astrophysics', correct: false, value: 0, quiz_id: 50)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 50)

	QuizOption.create!(option: 'Ahmedabad', correct: false, value: 0, quiz_id: 51)
	QuizOption.create!(option: 'Sriharikota', correct: false, value: 0, quiz_id: 51)
	QuizOption.create!(option: 'Pune', correct: false, value: 0, quiz_id: 51)
	QuizOption.create!(option: 'Thiruvananthapuram', correct: true, value: 1, quiz_id: 51)
	QuizOption.create!(option: 'Hyderabad', correct: false, value: 0, quiz_id: 51)

	QuizOption.create!(option: 'Tiger Woods', correct: false, value: 0, quiz_id: 52)
	QuizOption.create!(option: 'Steven Spielberg', correct: false, value: 0, quiz_id: 52)
	QuizOption.create!(option: 'Britney Spears', correct: true, value: 1, quiz_id: 52)
	QuizOption.create!(option: 'Michael Jordan', correct: false, value: 0, quiz_id: 52)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 52)

	QuizOption.create!(option: 'Rajiv Gandhi', correct: false, value: 0, quiz_id: 53)
	QuizOption.create!(option: 'Jagjiwan Ram', correct: false, value: 0, quiz_id: 53)
	QuizOption.create!(option: 'Jawaharlal Nehru', correct: false, value: 0, quiz_id: 53)
	QuizOption.create!(option: 'Lal Bahadur Shastri', correct: true, value: 1, quiz_id: 53)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 53)

	QuizOption.create!(option: 'Ranchi', correct: false, value: 0, quiz_id: 54)
	QuizOption.create!(option: 'Rourkela', correct: false, value: 0, quiz_id: 54)
	QuizOption.create!(option: 'Asansol', correct: false, value: 0, quiz_id: 54)
	QuizOption.create!(option: 'Tatanagar', correct: true, value: 1, quiz_id: 54)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 54)

	QuizOption.create!(option: 'Journalism', correct: false, value: 0, quiz_id: 55)
	QuizOption.create!(option: 'Literature', correct: false, value: 0, quiz_id: 55)
	QuizOption.create!(option: 'Acting', correct: true, value: 1, quiz_id: 55)
	QuizOption.create!(option: 'Acting', correct: false, value: 0, quiz_id: 55)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 55)

	QuizOption.create!(option: 'Commercial art', correct: false, value: 0, quiz_id: 56)
	QuizOption.create!(option: 'Classical music', correct: false, value: 0, quiz_id: 56)
	QuizOption.create!(option: 'Classical dance', correct: false, value: 0, quiz_id: 56)
	QuizOption.create!(option: 'Direction of films', correct: true, value: 1, quiz_id: 56)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 56)

	QuizOption.create!(option: 'Sardar Ukil', correct: true, value: 1, quiz_id: 57)
	QuizOption.create!(option: 'Uday Shanker', correct: false, value: 0, quiz_id: 57)
	QuizOption.create!(option: 'V. Shantaram', correct: false, value: 0, quiz_id: 57)
	QuizOption.create!(option: 'Yusuf Meherally', correct: false, value: 0, quiz_id: 57)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 57)

	QuizOption.create!(option: 'Social service', correct: false, value: 0, quiz_id: 58)
	QuizOption.create!(option: 'Trade Unionism', correct: false, value: 0, quiz_id: 58)
	QuizOption.create!(option: 'Journalism', correct: true, value: 1, quiz_id: 58)
	QuizOption.create!(option: 'Politics', correct: false, value: 0, quiz_id: 58)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 58)

	QuizOption.create!(option: 'Walter Scott', correct: false, value: 0, quiz_id: 59)
	QuizOption.create!(option: 'Gen. Rommel', correct: true, value: 1, quiz_id: 59)
	QuizOption.create!(option: 'Eisenhower', correct: false, value: 0, quiz_id: 59)
	QuizOption.create!(option: 'Bismarck', correct: false, value: 0, quiz_id: 59)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 59)

	QuizOption.create!(option: 'Chennai', correct: false, value: 0, quiz_id: 60)
	QuizOption.create!(option: 'Hyderabad', correct: true, value: 1, quiz_id: 60)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 60)
	QuizOption.create!(option: 'Pant Nagar', correct: false, value: 0, quiz_id: 60)
	QuizOption.create!(option: 'Delhi', correct: false, value: 0, quiz_id: 60)

	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 61)
	QuizOption.create!(option: 'Lucknow', correct: false, value: 0, quiz_id: 61)
	QuizOption.create!(option: 'Dehradun', correct: true, value: 1, quiz_id: 61)
	QuizOption.create!(option: 'Kanpur', correct: false, value: 0, quiz_id: 61)
	QuizOption.create!(option: 'Hyderabad', correct: false, value: 0, quiz_id: 61)

	QuizOption.create!(option: 'Pune', correct: false, value: 0, quiz_id: 62)
	QuizOption.create!(option: 'Surat', correct: false, value: 0, quiz_id: 62)
	QuizOption.create!(option: 'Gurgaon', correct: true, value: 1, quiz_id: 62)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 62)
	QuizOption.create!(option: 'Chennai', correct: false, value: 0, quiz_id: 62)

	QuizOption.create!(option: 'Delhi', correct: true, value: 1, quiz_id: 63)
	QuizOption.create!(option: 'Belgaum', correct: false, value: 0, quiz_id: 63)
	QuizOption.create!(option: 'Hyderabad', correct: false, value: 0, quiz_id: 63)
	QuizOption.create!(option: 'Mount abu', correct: false, value: 0, quiz_id: 63)
	QuizOption.create!(option: 'Chennai', correct: false, value: 0, quiz_id: 63)

	QuizOption.create!(option: 'Nanded', correct: false, value: 0, quiz_id: 64)
	QuizOption.create!(option: 'Aurangabad', correct: true, value: 1, quiz_id: 64)
	QuizOption.create!(option: 'Parbhani', correct: false, value: 0, quiz_id: 64)
	QuizOption.create!(option: 'Nagpur', correct: false, value: 0, quiz_id: 64)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 64)

	QuizOption.create!(option: 'Andhra Pradesh', correct: false, value: 0, quiz_id: 65)
	QuizOption.create!(option: 'Uttar Pradesh', correct: false, value: 0, quiz_id: 65)
	QuizOption.create!(option: 'Wesh Bengal', correct: true, value: 1, quiz_id: 65)
	QuizOption.create!(option: 'New Delhi', correct: false, value: 0, quiz_id: 65)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 65)

	QuizOption.create!(option: 'Chandigarh', correct: false, value: 0, quiz_id: 66)
	QuizOption.create!(option: 'Haryana', correct: false, value: 0, quiz_id: 66)
	QuizOption.create!(option: 'Punjab', correct: false, value: 0, quiz_id: 66)
	QuizOption.create!(option: 'Amritsar', correct: true, value: 1, quiz_id: 66)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 66)

	QuizOption.create!(option: 'Kathak', correct: true, value: 1, quiz_id: 67)
	QuizOption.create!(option: 'Kathakali', correct: false, value: 0, quiz_id: 67)
	QuizOption.create!(option: 'Odissi', correct: false, value: 0, quiz_id: 67)
	QuizOption.create!(option: 'Kuchipudi', correct: false, value: 0, quiz_id: 67)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 67)

	QuizOption.create!(option: 'Satish Gujral', correct: false, value: 0, quiz_id: 68)
	QuizOption.create!(option: 'Nandlal Bose', correct: false, value: 0, quiz_id: 68)
	QuizOption.create!(option: 'K.D. Tendulkar', correct: false, value: 0, quiz_id: 68)
	QuizOption.create!(option: 'Amrita Shergill', correct: true, value: 1, quiz_id: 68)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 68)

	QuizOption.create!(option: '1 and 2', correct: false, value: 0, quiz_id: 69)
	QuizOption.create!(option: '2 and 3', correct: false, value: 0, quiz_id: 69)
	QuizOption.create!(option: '1 and 3', correct: false, value: 0, quiz_id: 69)
	QuizOption.create!(option: '2', correct: false, value: 0, quiz_id: 69)
	QuizOption.create!(option: '1, 2 and 3', correct: true, value: 1, quiz_id: 69)

	QuizOption.create!(option: 'Guru Gobind Singh', correct: false, value: 0, quiz_id: 70)
	QuizOption.create!(option: 'M.S. Golwalkar', correct: false, value: 0, quiz_id: 70)
	QuizOption.create!(option: 'Raj Guru', correct: false, value: 0, quiz_id: 70)
	QuizOption.create!(option: 'Rabindranath Tagore', correct: true, value: 1, quiz_id: 70)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 70)

	QuizOption.create!(option: 'Manipuri', correct: false, value: 0, quiz_id: 71)
	QuizOption.create!(option: 'Bharatnatyam', correct: false, value: 0, quiz_id: 71)
	QuizOption.create!(option: 'Kuchipudi', correct: false, value: 0, quiz_id: 71)
	QuizOption.create!(option: 'Kathak', correct: true, value: 1, quiz_id: 71)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 71)

	QuizOption.create!(option: 'sitar', correct: false, value: 0, quiz_id: 72)
	QuizOption.create!(option: 'flute', correct: false, value: 0, quiz_id: 72)
	QuizOption.create!(option: 'tabla', correct: false, value: 0, quiz_id: 72)
	QuizOption.create!(option: 'santoor', correct: true, value: 1, quiz_id: 72)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 72)

	QuizOption.create!(option: 'Marmugao', correct: true, value: 1, quiz_id: 73)
	QuizOption.create!(option: 'Cochin', correct: false, value: 0, quiz_id: 73)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 73)
	QuizOption.create!(option: 'Mumbai', correct: false, value: 0, quiz_id: 73)
	QuizOption.create!(option: 'Kolkata', correct: false, value: 0, quiz_id: 73)

	QuizOption.create!(option: 'Northern', correct: false, value: 0, quiz_id: 74)
	QuizOption.create!(option: 'Southern', correct: false, value: 0, quiz_id: 74)
	QuizOption.create!(option: 'Centreal', correct: false, value: 0, quiz_id: 74)
	QuizOption.create!(option: 'Western', correct: true, value: 1, quiz_id: 74)
	QuizOption.create!(option: 'None of th eabove', correct: false, value: 0, quiz_id: 74)

	QuizOption.create!(option: '2 and 4', correct: false, value: 0, quiz_id: 75)
	QuizOption.create!(option: '1, 2 and 3', correct: true, value: 1, quiz_id: 75)
	QuizOption.create!(option: '1, 3 and 4', correct: false, value: 0, quiz_id: 75)
	QuizOption.create!(option: '2 and 3', correct: false, value: 0, quiz_id: 75)
	QuizOption.create!(option: '1, 2, 3 and 4', correct: false, value: 0, quiz_id: 75)

	QuizOption.create!(option: 'to be inducted into the Indian Navy', correct: false, value: 0, quiz_id: 76)
	QuizOption.create!(option: 'doctor to create a test tube baby', correct: false, value: 0, quiz_id: 76)
	QuizOption.create!(option: 'pilot to fly an aircraft Solo', correct: true, value: 1, quiz_id: 76)
	QuizOption.create!(option: 'Ambassador to a foreign country', correct: false, value: 0, quiz_id: 76)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 76)

	QuizOption.create!(option: 'Maharashtra', correct: false, value: 0, quiz_id: 77)
	QuizOption.create!(option: 'Bihar', correct: false, value: 0, quiz_id: 77)
	QuizOption.create!(option: 'West Bengal', correct: false, value: 0, quiz_id: 77)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 77)
	QuizOption.create!(option: 'None of these', correct: true, value: 1, quiz_id: 77)

	QuizOption.create!(option: 'Muthuswami Dikshitar', correct: true, value: 1, quiz_id: 78)
	QuizOption.create!(option: 'Thyagaraja', correct: false, value: 0, quiz_id: 78)
	QuizOption.create!(option: 'Swami Thirunal', correct: false, value: 0, quiz_id: 78)
	QuizOption.create!(option: 'Purandardasa', correct: false, value: 0, quiz_id: 78)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 78)

	QuizOption.create!(option: 'Elliot Handler', correct: false, value: 0, quiz_id: 79)
	QuizOption.create!(option: 'Daniela Ullyett', correct: false, value: 0, quiz_id: 79)
	QuizOption.create!(option: 'Ruth Handler', correct: true, value: 1, quiz_id: 79)
	QuizOption.create!(option: 'Ann Johnson', correct: false, value: 0, quiz_id: 79)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 79)

	QuizOption.create!(option: 'the office of the P.M.', correct: false, value: 0, quiz_id: 80)
	QuizOption.create!(option: 'the office of teh NFDC', correct: false, value: 0, quiz_id: 80)
	QuizOption.create!(option: 'the Doordarshan C.P.C.', correct: false, value: 0, quiz_id: 80)
	QuizOption.create!(option: 'the office of Director General of Doordarshan', correct: true, value: 1, quiz_id: 80)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 80)

	QuizOption.create!(option: '1835', correct: false, value: 0, quiz_id: 81)
	QuizOption.create!(option: '1853', correct: true, value: 1, quiz_id: 81)
	QuizOption.create!(option: '1917', correct: false, value: 0, quiz_id: 81)
	QuizOption.create!(option: '1916', correct: false, value: 0, quiz_id: 81)
	QuizOption.create!(option: '1923', correct: false, value: 0, quiz_id: 81)

	QuizOption.create!(option: 'Delhi', correct: false, value: 0, quiz_id: 82)
	QuizOption.create!(option: 'Chandigarh', correct: true, value: 1, quiz_id: 82)
	QuizOption.create!(option: 'Chennai', correct: false, value: 0, quiz_id: 82)
	QuizOption.create!(option: 'Mumbai', correct: false, value: 0, quiz_id: 82)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 82)

	QuizOption.create!(option: 'Sarang - V.C. Jog', correct: false, value: 0, quiz_id: 83)
	QuizOption.create!(option: 'Painting - Gaganendranath', correct: false, value: 0, quiz_id: 83)
	QuizOption.create!(option: 'Dance - Rukmini Devi Arundale', correct: false, value: 0, quiz_id: 83)
	QuizOption.create!(option: 'Violin - Ravi Verma', correct: true, value: 1, quiz_id: 83)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 83)

	QuizOption.create!(option: 'direction', correct: false, value: 0, quiz_id: 84)
	QuizOption.create!(option: 'costum designing', correct: true, value: 1, quiz_id: 84)
	QuizOption.create!(option: 'photography', correct: false, value: 0, quiz_id: 84)
	QuizOption.create!(option: 'script writing', correct: false, value: 0, quiz_id: 84)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 84)

	QuizOption.create!(option: 'Ravi Shankar', correct: true, value: 1, quiz_id: 85)
	QuizOption.create!(option: 'Amjad Ali Khan', correct: false, value: 0, quiz_id: 85)
	QuizOption.create!(option: 'M.S. Subbulakshmi', correct: false, value: 0, quiz_id: 85)
	QuizOption.create!(option: 'Zubin Mehta', correct: false, value: 0, quiz_id: 85)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 85)

	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 86)
	QuizOption.create!(option: 'Dehradun', correct: true, value: 1, quiz_id: 86)
	QuizOption.create!(option: 'Hyderabad', correct: false, value: 0, quiz_id: 86)
	QuizOption.create!(option: 'Abu Road', correct: false, value: 0, quiz_id: 86)
	QuizOption.create!(option: 'Bangalore', correct: false, value: 0, quiz_id: 86)

	QuizOption.create!(option: 'Gujarat', correct: false, value: 0, quiz_id: 87)
	QuizOption.create!(option: 'Karanataka', correct: false, value: 0, quiz_id: 87)
	QuizOption.create!(option: 'Goa', correct: false, value: 0, quiz_id: 87)
	QuizOption.create!(option: 'Tamilnadu', correct: false, value: 0, quiz_id: 87)
	QuizOption.create!(option: 'Maharashtra', correct: true, value: 1, quiz_id: 87)

	QuizOption.create!(option: 'Bombay', correct: false, value: 0, quiz_id: 88)
	QuizOption.create!(option: 'Trivandrum', correct: false, value: 0, quiz_id: 88)
	QuizOption.create!(option: 'Pondicherry', correct: false, value: 0, quiz_id: 88)
	QuizOption.create!(option: 'Kanyakumari', correct: true, value: 1, quiz_id: 88)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 88)

	QuizOption.create!(option: 'Social Worker', correct: false, value: 0, quiz_id: 89)
	QuizOption.create!(option: 'Economist', correct: false, value: 0, quiz_id: 89)
	QuizOption.create!(option: 'Veteran Gandhian', correct: true, value: 1, quiz_id: 89)
	QuizOption.create!(option: 'Scientist', correct: false, value: 0, quiz_id: 89)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 89)

	QuizOption.create!(option: 'West Bengal', correct: true, value: 1, quiz_id: 90)
	QuizOption.create!(option: 'Meghalaya', correct: false, value: 0, quiz_id: 90)
	QuizOption.create!(option: 'Tripura', correct: false, value: 0, quiz_id: 90)
	QuizOption.create!(option: 'Assam', correct: false, value: 0, quiz_id: 90)
	QuizOption.create!(option: 'None of the above', correct: false, value: 0, quiz_id: 90)

end
